Feat/sig-6
GDSCUTM-CommunityProjects/SIGNify pull request #2
Opened 2022-02-04 21:46 UTC by kavyamehta

Finished creating frontend settings page. 

ACCEPTANCE CRITERIA:Upon clicking the settings icon on the main page, user should be directed to a separate page called Settings. This page should show the user the different controls such as the light/dark mode, size of text, and theme colour.

2022-02-04 21:56 UTC, Blizzard416 approved these changes
All good :)

2022-02-04 23:18 UTC, milindvishnoi requested changes
The settings page looks greatt!

2022-02-04 23:18 UTC, milindvishnoi commented on frontend/lib/main.dart
> -  Widget build(BuildContext context) {
Removing this part removes the light/dark mode stuff. Please fix this!

2022-02-04 23:18 UTC, milindvishnoi commented on frontend/lib/main.dart
> -// Custom Green for app
This is the custom green of our app.

2022-02-04 23:18 UTC, milindvishnoi commented on frontend/lib/settings.dart
> +                  style: TextStyle(fontWeight: FontWeight.w900, color: Colors.teal),
Please use the custom color, mentioned above.

2022-02-08 21:45 UTC, milindvishnoi commented
Everything seems to be working fine. Great job!

2022-02-08 21:45 UTC, merged